
- name: base | software | docker-compose | download binary
  become_user: root
  ansible.builtin.shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: base | software | docker-compose | make binary executable
  become_user: root
  ansible.builtin.shell: chmod +x /usr/local/bin/docker-compose
