# IF this gets the ERROR: It is held by process 1732 (packagekitd)
# Run it again or do:
#
#   systemctl stop packagekit
#
# If, for some reason, you wish to disable it, you can use:
#
#   systemctl disable packagekit
#
- name: base | software | docker | Install required system packages
  become_user: root
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'software-properties-common', 'python3-setuptools']

- name: base | software | docker | Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: base | software | docker | Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: base | software | docker | Update apt and install docker-ce
  apt: 
    update_cache: yes 
    name: docker-ce 
    state: latest

# YOU WILL NEED TO FULLY REBOOT THE PC FOR THE GROUP TO TAKE EFFECT
- name: base | software | docker | Add user to docker group
  become_user: root
  user: 
    name: ivo
    groups: docker
    append: yes
