
- name: base | software | vs code | download and trust microsoft key
  become_user: root
  ansible.builtin.shell: |
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
    sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
    rm -f packages.microsoft.gpg

- name: base | software | vs code | install package with apy
  become_user: root
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'code']
